<?xml version="1.0" ?>
<robot name="shelf" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find urdf_to_scene)/config/utils.xacro" />

  <!-- Generic Open Shelf macro -->
  <!-- TODO add option for an open and a closed shelf -->
  <xacro:macro name="shelf" params="name
                                    frame_id
                                    xyz:='0 0 0'
                                    rpy:='0 0 0'
                                    dimensions:='0.6 1.5 1.25'
                                    h_boards:=5
                                    v_boards:=3
                                    h_board_thickness:=0.02
                                    v_board_thickness:=0.02
                                    back_board:=false
                                    dl:=_">

  <!-- Property -->
  <xacro:property name="root" value="${name}" />
  <xacro:property name="hboard_gap" value="${float(dimensions.split()[2])/h_boards}" />
  <xacro:property name="vboard_gap" value="${float(dimensions.split()[1])/(1 + v_boards)}" />

  <xacro:property name="dim_x" value="${dimensions.split()[0]}" />
  <xacro:property name="dim_y" value="${dimensions.split()[1]}" />
  <xacro:property name="dim_z" value="${dimensions.split()[2]}" />

  <xacro:property name="hboard_dim_x" value="${dim_x}" />
  <xacro:property name="hboard_dim_y" value="${vboard_gap + v_board_thickness/2}" />
  <xacro:property name="hboard_dim_z" value="${h_board_thickness}" />
  <xacro:property name="hboard_dimensions" value="${hboard_dim_x} ${hboard_dim_y} ${hboard_dim_z}" />

  <xacro:property name="vboard_dim_x" value="${dim_x}" />
  <xacro:property name="vboard_dim_y" value="${v_board_thickness}" />
  <xacro:property name="vboard_dim_z" value="${dim_z}" />
  <xacro:property name="vboard_dimensions" value="${vboard_dim_x} ${vboard_dim_y} ${vboard_dim_z}" />

  <!-- Base link -->
  <xacro:dummy name="${root}"
               frame_id="${frame_id}"
               xyz="${xyz}" rpy="${rpy}" />

  <!-- Leftmost and rightmost vertical boards -->
  <xacro:framebox name="${root}${dl}vboard1"
                  frame_id="${root}"
                  dimensions="${vboard_dimensions}"
                  xyz="0 ${-(dim_y/2 - v_board_thickness/2)} 0"/>

  <xacro:framebox name="${root}${dl}vboard${v_boards + 2}"
                  frame_id="${root}"
                  dimensions="${vboard_dimensions}"
                  xyz="0 ${dim_y/2 - v_board_thickness/2} 0"/>
  
  <!-- Vertical inside boards -->
  <xacro:macro name="loopvboard" params="current:=0 until:=^">
    <xacro:if value="${until > current}">
      <xacro:framebox name="${root}${dl}vboard${current+2}"
                      frame_id="${root}${dl}vboard1/bottom"
                      dimensions="${vboard_dimensions}"
                      xyz="0 ${(current+1)*vboard_gap- v_board_thickness/2} 0"/>
      <xacro:loopvboard current="${current+1}"/>
    </xacro:if>
  </xacro:macro>

  <xacro:loopvboard until="${v_boards}"/>

  <!-- Horizontal boards -->
  <xacro:macro name="loophboard" params="current:=0 index:=^ until:=^">
    <xacro:if value="${until > current}">
      <xacro:framebox name="${root}${dl}board${index*h_boards+current+1}"
                 frame_id="${root}${dl}vboard${index+1}/bottom"
                 dimensions="${hboard_dimensions}"
                 xyz="0 ${(vboard_gap - v_board_thickness/2)/2} ${(current + 1)*hboard_gap - h_board_thickness}"/>
      <xacro:loophboard current="${current+1}"/>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="loophrowboard" params="current:=0 until:=^">
    <xacro:if value="${until > current}">
      <xacro:loophboard index="${current}" until="${h_boards}"/>
      <xacro:loophrowboard current="${current+1}"/>
    </xacro:if>
  </xacro:macro>

  <xacro:loophrowboard until="${v_boards + 1}"/>

  <!-- Back board -->
  <xacro:if value="${back_board}">
    <xacro:framebox name="${root}${dl}backboard"
                    frame_id="${root}"
                    dimensions="${v_board_thickness} ${dim_y} ${dim_z}"
                    xyz="${-dim_x/2} 0 0"/>
  </xacro:if> 

  </xacro:macro>
</robot>
